## DAY 1

In [ ]:
from google.colab import files 
df = files.upload()

Saving text_emotion.csv to text_emotion (1).csv

In [ ]:
import pandas as pd
import io
Result = pd.read_csv(io.BytesIO(df['text_emotion.csv']))

In [ ]:
Result.head(5)

,tweet_id,sentiment,author,content
0,1956967341,empty,xoshayzers,@tiffanylue i know i was listenin to bad habi...
1,1956967666,sadness,wannamama,Layin n bed with a headache ughhhh...waitin o...
2,1956967696,sadness,coolfunky,Funeral ceremony...gloomy friday...
3,1956967789,enthusiasm,czareaquino,wants to hang out with friends SOON!
4,1956968416,neutral,xkilljoyx,@dannycastillo We want to trade with someone w...

In [ ]:
Result.tail(5)

,tweet_id,sentiment,author,content
39995,1753918954,neutral,showMe_Heaven,@JohnLloydTaylor
39996,1753919001,love,drapeaux,Happy Mothers Day All my love
39997,1753919005,love,JenniRox,Happy Mother's Day to all the mommies out ther...
39998,1753919043,happiness,ipdaman1,@niariley WASSUP BEAUTIFUL!!! FOLLOW ME!! PEE...
39999,1753919049,love,Alpharalpha,@mopedronin bullet train from tokyo the gf ...

In [ ]:
df1 = Result.iloc[6:24]
df1

,tweet_id,sentiment,author,content
6,1956968487,sadness,ShansBee,"I should be sleep, but im not! thinking about ..."
7,1956968636,worry,mcsleazy,Hmmm. http://www.djhero.com/ is down
8,1956969035,sadness,nic0lepaula,@charviray Charlene my love. I miss you
9,1956969172,sadness,Ingenue_Em,@kelcouch I'm sorry at least it's Friday?
10,1956969456,neutral,feinyheiny,cant fall asleep
11,1956969531,worry,dudeitsmanda,Choked on her retainers
12,1956970047,sadness,Danied32,Ugh! I have to beat this stupid song to get to...
13,1956970424,sadness,Samm_xo,@BrodyJenner if u watch the hills in london u ...
14,1956970860,surprise,okiepeanut93,Got the news
15,1956971077,sadness,Sim_34,The storm is here and the electricity is gone
16,1956971170,love,poppygallico,@annarosekerr agreed
17,1956971206,sadness,brokenangel1982,So sleepy again and it's not even that late. I...
18,1956971473,worry,LCJ82,@PerezHilton lady gaga tweeted about not being...
19,1956971586,sadness,cleepow,How are YOU convinced that I have always wante...
20,1956971981,worry,andreagauster,@raaaaaaek oh too bad! I hope it gets better. ...
21,1956972097,fun,schiz0phren1c,"Wondering why I'm awake at 7am,writing a new s..."
22,1956972116,neutral,jansc,No Topic Maps talks at the Balisage Markup Con...
23,1956972270,worry,sweet8181,I ate Something I don't know what it is... Why...

In [ ]:
df2 = Result.iloc[9]
df2

tweet_id                                     1956969172
sentiment                                       sadness
author                                       Ingenue_Em
content      @kelcouch I'm sorry  at least it's Friday?
Name: 9, dtype: object

In [ ]:
X=Result[['tweet_id','sentiment','author']]
Y=Result[['content']]
Y

                                                 content
0      @tiffanylue i know  i was listenin to bad habi...
1      Layin n bed with a headache  ughhhh...waitin o...
2                    Funeral ceremony...gloomy friday...
3                   wants to hang out with friends SOON!
4      @dannycastillo We want to trade with someone w...
...                                                  ...
39995                                   @JohnLloydTaylor
39996                     Happy Mothers Day  All my love
39997  Happy Mother's Day to all the mommies out ther...
39998  @niariley WASSUP BEAUTIFUL!!! FOLLOW ME!!  PEE...
39999  @mopedronin bullet train from tokyo    the gf ...

[40000 rows x 1 columns]

In [ ]:
Result.shape

(40000, 4)